### ISSUE TITLE
Lot01 - Partage de coran (TAKHARROUBT)

### ISSUE THREAD

**Issue by belhadj83** [A-I-M-F/aimf-app#5]
En tant que utilisateur connecté à l'application, dans cet écran je peux choisir une partie de coran à lire. 

**Description** : 

Dans cet écran on trouvera les différentes parties de coran (TIKHARROUBIN) à lire du chapitre  AL BAKARA jusqu'au a fin (AL KHATIMA).  A coté de chaque partie, on trouvera un bouton on-off ![on](https://user-images.githubusercontent.com/43602498/59550565-68436d00-8f6c-11e9-951e-20c8c6058727.jpg) ![off](https://user-images.githubusercontent.com/43602498/59550628-21a24280-8f6d-11e9-9c88-1a8132e9b859.jpg) pour prendre la partie. Ce bouton devient grisé si une autre personne a déjà pris la partie associée. A l'activation du bouton, une alerte s'affiche pour confirmer la prise en compte de cette partie de courson. Cette alerte toit contenir le message suivant : "Veuillez confirmer la prise en compte de cette TAKHRROUBT".

Cette liste se réinitialise après chaque khetma hebdomadaire par un administrateur depuis un écran dédié.

**Comment by Abderrazzak87** [comment]
Done
