### ISSUE TITLE
Lot01 - Admin : Gestion de partage de coran

### ISSUE THREAD

**Issue by belhadj83** [A-I-M-F/aimf-app#7]
En tant que administrateur je peux gérer les prises des TIKHARROUBIN.

**Description:**

Dans le même écran détaillé dans une issue (Lot1 - Partage de coran (TAKHARROUBT) : https://github.com/ilyeSudo/AIMFAPP/issues/5), un administrateur aura la possibilité de gérer les parties de Coran comme suit :

- Il peux programmer (initialiser les parties de coran) une nouvelle session
- Il L'aura la possibilité de prendre ou de libérer une TAKHARROUBT
- Il a la possibilité de visualiser le nom de la personne qui a pris la TAKHARROUBT

L'administrateur pourra initialiser une session ou modifier les dates de la session en cours et ceci en appuyant sur l'un des deux boutons (Initialiser/Modifier) qui s'affichent en bas d'écran.

1. Cas de dinitialisation : une popup s'affiche permet de saisir les date et heures de début et la fin de la session avec un message de confirmation. Une fois les dates saisies l'utilisateur appuie sur ok pour confirmer la création d'une nouvelle session, ce qui permet de libérer toutes les parties de coran.

2. Cas de modification :  Même cas pour l'intialisation à l'exception les parties de coran ne seront pa modifiées.

Tous les parties de coran restent grisées (désactivées) tant que la session n'est pas encore ouverte

A la création d'une nouvelle session, tous les utilisateurs connectés à l'application recevront une notification système l'informant sur cette session

**Comment by Abderrazzak87** [comment]
Terminé
